"""v3 operation metadata for generic Python wrappers."""

OPERATIONS = {'fieldwork_attachment_content': {'id': 'fieldwork_attachment_content',
                                  'method': 'GET',
                                  'path': '/api/v3/fieldwork/attachments/content',
                                  'params': [{'name': 'Account-Type',
                                              'in': 'header',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'work_id',
                                              'in': 'query',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'object_key',
                                              'in': 'query',
                                              'required': True,
                                              'explode': True}],
                                  'content': None,
                                  'security': [{'bearer': []}]},
 'fieldwork_attachment_download': {'id': 'fieldwork_attachment_download',
                                   'method': 'GET',
                                   'path': '/api/v3/fieldwork/attachments/download',
                                   'params': [{'name': 'work_id',
                                               'in': 'query',
                                               'required': True,
                                               'explode': True},
                                              {'name': 'object_key',
                                               'in': 'query',
                                               'required': True,
                                               'explode': True},
                                              {'name': 'expires',
                                               'in': 'query',
                                               'required': True,
                                               'explode': True},
                                              {'name': 'signature',
                                               'in': 'query',
                                               'required': True,
                                               'explode': True}],
                                   'content': None,
                                   'security': []},
 'fieldwork_receipt_get': {'id': 'fieldwork_receipt_get',
                           'method': 'GET',
                           'path': '/api/v3/fieldwork/command-receipts',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'operation',
                                       'in': 'query',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'command_key',
                                       'in': 'query',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'query',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'plant_id',
                                       'in': 'query',
                                       'required': False,
                                       'explode': True}],
                           'content': None,
                           'security': [{'bearer': []}]},
 'fieldwork_message_previews': {'id': 'fieldwork_message_previews',
                                'method': 'GET',
                                'path': '/api/v3/fieldwork/latest-message-previews',
                                'params': [{'name': 'Account-Type',
                                            'in': 'header',
                                            'required': False,
                                            'explode': True},
                                           {'name': 'work_id',
                                            'in': 'query',
                                            'required': True,
                                            'explode': True}],
                                'content': None,
                                'security': [{'bearer': []}]},
 'fieldwork_notifications_list': {'id': 'fieldwork_notifications_list',
                                  'method': 'GET',
                                  'path': '/api/v3/fieldwork/notifications',
                                  'params': [{'name': 'Account-Type',
                                              'in': 'header',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'plant_id',
                                              'in': 'query',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'work_id',
                                              'in': 'query',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'unread_only',
                                              'in': 'query',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'cursor',
                                              'in': 'query',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'limit',
                                              'in': 'query',
                                              'required': False,
                                              'explode': True}],
                                  'content': None,
                                  'security': [{'bearer': []}]},
 'fieldwork_notifications_summary': {'id': 'fieldwork_notifications_summary',
                                     'method': 'GET',
                                     'path': '/api/v3/fieldwork/notifications/summary',
                                     'params': [{'name': 'Account-Type',
                                                 'in': 'header',
                                                 'required': False,
                                                 'explode': True},
                                                {'name': 'plant_id',
                                                 'in': 'query',
                                                 'required': False,
                                                 'explode': True}],
                                     'content': None,
                                     'security': [{'bearer': []}]},
 'fieldwork_notification_archive': {'id': 'fieldwork_notification_archive',
                                    'method': 'POST',
                                    'path': '/api/v3/fieldwork/notifications/{notification_id}/archive',
                                    'params': [{'name': 'Account-Type',
                                                'in': 'header',
                                                'required': False,
                                                'explode': True},
                                               {'name': 'notification_id',
                                                'in': 'path',
                                                'required': True,
                                                'explode': True}],
                                    'content': 'application/json',
                                    'security': [{'bearer': []}]},
 'fieldwork_notification_read': {'id': 'fieldwork_notification_read',
                                 'method': 'POST',
                                 'path': '/api/v3/fieldwork/notifications/{notification_id}/read',
                                 'params': [{'name': 'Account-Type',
                                             'in': 'header',
                                             'required': False,
                                             'explode': True},
                                            {'name': 'notification_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True}],
                                 'content': 'application/json',
                                 'security': [{'bearer': []}]},
 'fieldwork_participant_session_create': {'id': 'fieldwork_participant_session_create',
                                          'method': 'POST',
                                          'path': '/api/v3/fieldwork/participant-sessions',
                                          'params': [],
                                          'content': 'application/json',
                                          'security': [{'bearer': []}]},
 'fieldwork_plant_member_candidates': {'id': 'fieldwork_plant_member_candidates',
                                       'method': 'GET',
                                       'path': '/api/v3/fieldwork/plants/{plant_id}/member-candidates',
                                       'params': [{'name': 'Account-Type',
                                                   'in': 'header',
                                                   'required': False,
                                                   'explode': True},
                                                  {'name': 'search',
                                                   'in': 'query',
                                                   'required': False,
                                                   'explode': True},
                                                  {'name': 'organization_id',
                                                   'in': 'query',
                                                   'required': False,
                                                   'explode': True},
                                                  {'name': 'cursor',
                                                   'in': 'query',
                                                   'required': False,
                                                   'explode': True},
                                                  {'name': 'limit',
                                                   'in': 'query',
                                                   'required': False,
                                                   'explode': True},
                                                  {'name': 'plant_id',
                                                   'in': 'path',
                                                   'required': True,
                                                   'explode': True}],
                                       'content': None,
                                       'security': [{'bearer': []}]},
 'fieldwork_summary_get': {'id': 'fieldwork_summary_get',
                           'method': 'GET',
                           'path': '/api/v3/fieldwork/summary',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'plant_id',
                                       'in': 'query',
                                       'required': False,
                                       'explode': True}],
                           'content': None,
                           'security': [{'bearer': []}]},
 'fieldwork_templates_list': {'id': 'fieldwork_templates_list',
                              'method': 'GET',
                              'path': '/api/v3/fieldwork/templates',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'search',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'cursor',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'limit',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True}],
                              'content': None,
                              'security': [{'bearer': []}]},
 'fieldwork_works_list': {'id': 'fieldwork_works_list',
                          'method': 'GET',
                          'path': '/api/v3/fieldwork/works',
                          'params': [{'name': 'Account-Type',
                                      'in': 'header',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'search',
                                      'in': 'query',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'cursor',
                                      'in': 'query',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'limit',
                                      'in': 'query',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'plant_id',
                                      'in': 'query',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'status',
                                      'in': 'query',
                                      'required': False,
                                      'explode': True}],
                          'content': None,
                          'security': [{'bearer': []}]},
 'fieldwork_work_create': {'id': 'fieldwork_work_create',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_work_get': {'id': 'fieldwork_work_get',
                        'method': 'GET',
                        'path': '/api/v3/fieldwork/works/{work_id}',
                        'params': [{'name': 'Account-Type',
                                    'in': 'header',
                                    'required': False,
                                    'explode': True},
                                   {'name': 'work_id',
                                    'in': 'path',
                                    'required': True,
                                    'explode': True},
                                   {'name': 'surface',
                                    'in': 'query',
                                    'required': False,
                                    'explode': True},
                                   {'name': 'before',
                                    'in': 'query',
                                    'required': False,
                                    'explode': True}],
                        'content': None,
                        'security': [{'bearer': []}]},
 'fieldwork_work_archive': {'id': 'fieldwork_work_archive',
                            'method': 'POST',
                            'path': '/api/v3/fieldwork/works/{work_id}/archive',
                            'params': [{'name': 'Account-Type',
                                        'in': 'header',
                                        'required': False,
                                        'explode': True},
                                       {'name': 'Idempotency-Key',
                                        'in': 'header',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'work_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True}],
                            'content': 'application/json',
                            'security': [{'bearer': []}]},
 'fieldwork_work_clone': {'id': 'fieldwork_work_clone',
                          'method': 'POST',
                          'path': '/api/v3/fieldwork/works/{work_id}/clone',
                          'params': [{'name': 'Account-Type',
                                      'in': 'header',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'Idempotency-Key',
                                      'in': 'header',
                                      'required': True,
                                      'explode': True},
                                     {'name': 'work_id',
                                      'in': 'path',
                                      'required': True,
                                      'explode': True}],
                          'content': 'application/json',
                          'security': [{'bearer': []}]},
 'fieldwork_work_close': {'id': 'fieldwork_work_close',
                          'method': 'POST',
                          'path': '/api/v3/fieldwork/works/{work_id}/close',
                          'params': [{'name': 'Account-Type',
                                      'in': 'header',
                                      'required': False,
                                      'explode': True},
                                     {'name': 'Idempotency-Key',
                                      'in': 'header',
                                      'required': True,
                                      'explode': True},
                                     {'name': 'work_id',
                                      'in': 'path',
                                      'required': True,
                                      'explode': True}],
                          'content': 'application/json',
                          'security': [{'bearer': []}]},
 'fieldwork_item_create': {'id': 'fieldwork_item_create',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/items',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_item_complete': {'id': 'fieldwork_item_complete',
                             'method': 'POST',
                             'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/complete',
                             'params': [{'name': 'Account-Type',
                                         'in': 'header',
                                         'required': False,
                                         'explode': True},
                                        {'name': 'Idempotency-Key',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'work_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'item_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'fieldwork_item_map_reference_add': {'id': 'fieldwork_item_map_reference_add',
                                      'method': 'POST',
                                      'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/map-references/add',
                                      'params': [{'name': 'Account-Type',
                                                  'in': 'header',
                                                  'required': False,
                                                  'explode': True},
                                                 {'name': 'Idempotency-Key',
                                                  'in': 'header',
                                                  'required': True,
                                                  'explode': True},
                                                 {'name': 'work_id',
                                                  'in': 'path',
                                                  'required': True,
                                                  'explode': True},
                                                 {'name': 'item_id',
                                                  'in': 'path',
                                                  'required': True,
                                                  'explode': True}],
                                      'content': 'application/json',
                                      'security': [{'bearer': []}]},
 'fieldwork_item_map_references_sync': {'id': 'fieldwork_item_map_references_sync',
                                        'method': 'POST',
                                        'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/map-references/sync',
                                        'params': [{'name': 'Account-Type',
                                                    'in': 'header',
                                                    'required': False,
                                                    'explode': True},
                                                   {'name': 'Idempotency-Key',
                                                    'in': 'header',
                                                    'required': True,
                                                    'explode': True},
                                                   {'name': 'work_id',
                                                    'in': 'path',
                                                    'required': True,
                                                    'explode': True},
                                                   {'name': 'item_id',
                                                    'in': 'path',
                                                    'required': True,
                                                    'explode': True}],
                                        'content': 'application/json',
                                        'security': [{'bearer': []}]},
 'fieldwork_item_map_reference_remove': {'id': 'fieldwork_item_map_reference_remove',
                                         'method': 'POST',
                                         'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/map-references/{map_ref_id}/remove',
                                         'params': [{'name': 'Account-Type',
                                                     'in': 'header',
                                                     'required': False,
                                                     'explode': True},
                                                    {'name': 'Idempotency-Key',
                                                     'in': 'header',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'work_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'item_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'map_ref_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True}],
                                         'content': 'application/json',
                                         'security': [{'bearer': []}]},
 'fieldwork_item_mentions_set': {'id': 'fieldwork_item_mentions_set',
                                 'method': 'POST',
                                 'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/mentions/set',
                                 'params': [{'name': 'Account-Type',
                                             'in': 'header',
                                             'required': False,
                                             'explode': True},
                                            {'name': 'Idempotency-Key',
                                             'in': 'header',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'work_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'item_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True}],
                                 'content': 'application/json',
                                 'security': [{'bearer': []}]},
 'fieldwork_item_move': {'id': 'fieldwork_item_move',
                         'method': 'POST',
                         'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/move',
                         'params': [{'name': 'Account-Type',
                                     'in': 'header',
                                     'required': False,
                                     'explode': True},
                                    {'name': 'Idempotency-Key',
                                     'in': 'header',
                                     'required': True,
                                     'explode': True},
                                    {'name': 'work_id',
                                     'in': 'path',
                                     'required': True,
                                     'explode': True},
                                    {'name': 'item_id',
                                     'in': 'path',
                                     'required': True,
                                     'explode': True}],
                         'content': 'application/json',
                         'security': [{'bearer': []}]},
 'fieldwork_item_photos_add': {'id': 'fieldwork_item_photos_add',
                               'method': 'POST',
                               'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/photos/add',
                               'params': [{'name': 'Account-Type',
                                           'in': 'header',
                                           'required': False,
                                           'explode': True},
                                          {'name': 'Idempotency-Key',
                                           'in': 'header',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'work_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'item_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True}],
                               'content': 'application/json',
                               'security': [{'bearer': []}]},
 'fieldwork_item_photo_move': {'id': 'fieldwork_item_photo_move',
                               'method': 'POST',
                               'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/photos/{photo_id}/move',
                               'params': [{'name': 'Account-Type',
                                           'in': 'header',
                                           'required': False,
                                           'explode': True},
                                          {'name': 'Idempotency-Key',
                                           'in': 'header',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'work_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'item_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'photo_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True}],
                               'content': 'application/json',
                               'security': [{'bearer': []}]},
 'fieldwork_item_photo_remove': {'id': 'fieldwork_item_photo_remove',
                                 'method': 'POST',
                                 'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/photos/{photo_id}/remove',
                                 'params': [{'name': 'Account-Type',
                                             'in': 'header',
                                             'required': False,
                                             'explode': True},
                                            {'name': 'Idempotency-Key',
                                             'in': 'header',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'work_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'item_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'photo_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True}],
                                 'content': 'application/json',
                                 'security': [{'bearer': []}]},
 'fieldwork_item_remove': {'id': 'fieldwork_item_remove',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/remove',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'item_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_item_reopen': {'id': 'fieldwork_item_reopen',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/reopen',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'item_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_item_update': {'id': 'fieldwork_item_update',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/items/{item_id}/update',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'item_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_member_invite': {'id': 'fieldwork_member_invite',
                             'method': 'POST',
                             'path': '/api/v3/fieldwork/works/{work_id}/members/invite',
                             'params': [{'name': 'Account-Type',
                                         'in': 'header',
                                         'required': False,
                                         'explode': True},
                                        {'name': 'work_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'fieldwork_member_join': {'id': 'fieldwork_member_join',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/members/self/join',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_member_leave': {'id': 'fieldwork_member_leave',
                            'method': 'POST',
                            'path': '/api/v3/fieldwork/works/{work_id}/members/self/leave',
                            'params': [{'name': 'Account-Type',
                                        'in': 'header',
                                        'required': False,
                                        'explode': True},
                                       {'name': 'work_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True}],
                            'content': 'application/json',
                            'security': [{'bearer': []}]},
 'fieldwork_member_remove': {'id': 'fieldwork_member_remove',
                             'method': 'POST',
                             'path': '/api/v3/fieldwork/works/{work_id}/members/{member_id}/remove',
                             'params': [{'name': 'Account-Type',
                                         'in': 'header',
                                         'required': False,
                                         'explode': True},
                                        {'name': 'work_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'member_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'fieldwork_member_responsible_add': {'id': 'fieldwork_member_responsible_add',
                                      'method': 'POST',
                                      'path': '/api/v3/fieldwork/works/{work_id}/members/{member_id}/responsible/add',
                                      'params': [{'name': 'Account-Type',
                                                  'in': 'header',
                                                  'required': False,
                                                  'explode': True},
                                                 {'name': 'work_id',
                                                  'in': 'path',
                                                  'required': True,
                                                  'explode': True},
                                                 {'name': 'member_id',
                                                  'in': 'path',
                                                  'required': True,
                                                  'explode': True}],
                                      'content': 'application/json',
                                      'security': [{'bearer': []}]},
 'fieldwork_member_responsible_remove': {'id': 'fieldwork_member_responsible_remove',
                                         'method': 'POST',
                                         'path': '/api/v3/fieldwork/works/{work_id}/members/{member_id}/responsible/remove',
                                         'params': [{'name': 'Account-Type',
                                                     'in': 'header',
                                                     'required': False,
                                                     'explode': True},
                                                    {'name': 'work_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'member_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True}],
                                         'content': 'application/json',
                                         'security': [{'bearer': []}]},
 'fieldwork_message_create': {'id': 'fieldwork_message_create',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/messages',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_messages_read': {'id': 'fieldwork_messages_read',
                             'method': 'POST',
                             'path': '/api/v3/fieldwork/works/{work_id}/messages/read',
                             'params': [{'name': 'Account-Type',
                                         'in': 'header',
                                         'required': False,
                                         'explode': True},
                                        {'name': 'Idempotency-Key',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'work_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'fieldwork_message_get': {'id': 'fieldwork_message_get',
                           'method': 'GET',
                           'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'message_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': None,
                           'security': [{'bearer': []}]},
 'fieldwork_message_attachment_remove': {'id': 'fieldwork_message_attachment_remove',
                                         'method': 'POST',
                                         'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/attachments/remove',
                                         'params': [{'name': 'Account-Type',
                                                     'in': 'header',
                                                     'required': False,
                                                     'explode': True},
                                                    {'name': 'Idempotency-Key',
                                                     'in': 'header',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'work_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'message_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True}],
                                         'content': 'application/json',
                                         'security': [{'bearer': []}]},
 'fieldwork_message_map_reference_add': {'id': 'fieldwork_message_map_reference_add',
                                         'method': 'POST',
                                         'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/map-references/add',
                                         'params': [{'name': 'Account-Type',
                                                     'in': 'header',
                                                     'required': False,
                                                     'explode': True},
                                                    {'name': 'Idempotency-Key',
                                                     'in': 'header',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'work_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True},
                                                    {'name': 'message_id',
                                                     'in': 'path',
                                                     'required': True,
                                                     'explode': True}],
                                         'content': 'application/json',
                                         'security': [{'bearer': []}]},
 'fieldwork_message_map_reference_remove': {'id': 'fieldwork_message_map_reference_remove',
                                            'method': 'POST',
                                            'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/map-references/remove',
                                            'params': [{'name': 'Account-Type',
                                                        'in': 'header',
                                                        'required': False,
                                                        'explode': True},
                                                       {'name': 'Idempotency-Key',
                                                        'in': 'header',
                                                        'required': True,
                                                        'explode': True},
                                                       {'name': 'work_id',
                                                        'in': 'path',
                                                        'required': True,
                                                        'explode': True},
                                                       {'name': 'message_id',
                                                        'in': 'path',
                                                        'required': True,
                                                        'explode': True}],
                                            'content': 'application/json',
                                            'security': [{'bearer': []}]},
 'fieldwork_message_map_references_sync': {'id': 'fieldwork_message_map_references_sync',
                                           'method': 'POST',
                                           'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/map-references/sync',
                                           'params': [{'name': 'Account-Type',
                                                       'in': 'header',
                                                       'required': False,
                                                       'explode': True},
                                                      {'name': 'Idempotency-Key',
                                                       'in': 'header',
                                                       'required': True,
                                                       'explode': True},
                                                      {'name': 'work_id',
                                                       'in': 'path',
                                                       'required': True,
                                                       'explode': True},
                                                      {'name': 'message_id',
                                                       'in': 'path',
                                                       'required': True,
                                                       'explode': True}],
                                           'content': 'application/json',
                                           'security': [{'bearer': []}]},
 'fieldwork_message_photos_add': {'id': 'fieldwork_message_photos_add',
                                  'method': 'POST',
                                  'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/photos/add',
                                  'params': [{'name': 'Account-Type',
                                              'in': 'header',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'Idempotency-Key',
                                              'in': 'header',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'work_id',
                                              'in': 'path',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'message_id',
                                              'in': 'path',
                                              'required': True,
                                              'explode': True}],
                                  'content': 'application/json',
                                  'security': [{'bearer': []}]},
 'fieldwork_message_photo_move': {'id': 'fieldwork_message_photo_move',
                                  'method': 'POST',
                                  'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/photos/{photo_id}/move',
                                  'params': [{'name': 'Account-Type',
                                              'in': 'header',
                                              'required': False,
                                              'explode': True},
                                             {'name': 'Idempotency-Key',
                                              'in': 'header',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'work_id',
                                              'in': 'path',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'message_id',
                                              'in': 'path',
                                              'required': True,
                                              'explode': True},
                                             {'name': 'photo_id',
                                              'in': 'path',
                                              'required': True,
                                              'explode': True}],
                                  'content': 'application/json',
                                  'security': [{'bearer': []}]},
 'fieldwork_message_photo_remove': {'id': 'fieldwork_message_photo_remove',
                                    'method': 'POST',
                                    'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/photos/{photo_id}/remove',
                                    'params': [{'name': 'Account-Type',
                                                'in': 'header',
                                                'required': False,
                                                'explode': True},
                                               {'name': 'Idempotency-Key',
                                                'in': 'header',
                                                'required': True,
                                                'explode': True},
                                               {'name': 'work_id',
                                                'in': 'path',
                                                'required': True,
                                                'explode': True},
                                               {'name': 'message_id',
                                                'in': 'path',
                                                'required': True,
                                                'explode': True},
                                               {'name': 'photo_id',
                                                'in': 'path',
                                                'required': True,
                                                'explode': True}],
                                    'content': 'application/json',
                                    'security': [{'bearer': []}]},
 'fieldwork_reaction_remove': {'id': 'fieldwork_reaction_remove',
                               'method': 'POST',
                               'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/reaction/remove',
                               'params': [{'name': 'Account-Type',
                                           'in': 'header',
                                           'required': False,
                                           'explode': True},
                                          {'name': 'Idempotency-Key',
                                           'in': 'header',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'work_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'message_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True}],
                               'content': 'application/json',
                               'security': [{'bearer': []}]},
 'fieldwork_reaction_set': {'id': 'fieldwork_reaction_set',
                            'method': 'POST',
                            'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/reaction/set',
                            'params': [{'name': 'Account-Type',
                                        'in': 'header',
                                        'required': False,
                                        'explode': True},
                                       {'name': 'Idempotency-Key',
                                        'in': 'header',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'work_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'message_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True}],
                            'content': 'application/json',
                            'security': [{'bearer': []}]},
 'fieldwork_message_remove': {'id': 'fieldwork_message_remove',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/remove',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'message_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_message_update': {'id': 'fieldwork_message_update',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/messages/{message_id}/update',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'message_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_work_reopen': {'id': 'fieldwork_work_reopen',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/reopen',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'fieldwork_resources_list': {'id': 'fieldwork_resources_list',
                              'method': 'GET',
                              'path': '/api/v3/fieldwork/works/{work_id}/resources',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'kind',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'cursor',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'limit',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True}],
                              'content': None,
                              'security': [{'bearer': []}]},
 'fieldwork_schedule_update': {'id': 'fieldwork_schedule_update',
                               'method': 'POST',
                               'path': '/api/v3/fieldwork/works/{work_id}/schedules/{schedule_id}/update',
                               'params': [{'name': 'Account-Type',
                                           'in': 'header',
                                           'required': False,
                                           'explode': True},
                                          {'name': 'Idempotency-Key',
                                           'in': 'header',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'work_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True},
                                          {'name': 'schedule_id',
                                           'in': 'path',
                                           'required': True,
                                           'explode': True}],
                               'content': 'application/json',
                               'security': [{'bearer': []}]},
 'fieldwork_section_create': {'id': 'fieldwork_section_create',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/sections',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_section_move': {'id': 'fieldwork_section_move',
                            'method': 'POST',
                            'path': '/api/v3/fieldwork/works/{work_id}/sections/{section_id}/move',
                            'params': [{'name': 'Account-Type',
                                        'in': 'header',
                                        'required': False,
                                        'explode': True},
                                       {'name': 'Idempotency-Key',
                                        'in': 'header',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'work_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'section_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True}],
                            'content': 'application/json',
                            'security': [{'bearer': []}]},
 'fieldwork_section_remove': {'id': 'fieldwork_section_remove',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/sections/{section_id}/remove',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'section_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_section_rename': {'id': 'fieldwork_section_rename',
                              'method': 'POST',
                              'path': '/api/v3/fieldwork/works/{work_id}/sections/{section_id}/rename',
                              'params': [{'name': 'Account-Type',
                                          'in': 'header',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'Idempotency-Key',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'work_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'section_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True}],
                              'content': 'application/json',
                              'security': [{'bearer': []}]},
 'fieldwork_work_seen': {'id': 'fieldwork_work_seen',
                         'method': 'POST',
                         'path': '/api/v3/fieldwork/works/{work_id}/seen',
                         'params': [{'name': 'Account-Type',
                                     'in': 'header',
                                     'required': False,
                                     'explode': True},
                                    {'name': 'work_id',
                                     'in': 'path',
                                     'required': True,
                                     'explode': True}],
                         'content': 'application/json',
                         'security': [{'bearer': []}]},
 'fieldwork_work_update': {'id': 'fieldwork_work_update',
                           'method': 'POST',
                           'path': '/api/v3/fieldwork/works/{work_id}/update',
                           'params': [{'name': 'Account-Type',
                                       'in': 'header',
                                       'required': False,
                                       'explode': True},
                                      {'name': 'Idempotency-Key',
                                       'in': 'header',
                                       'required': True,
                                       'explode': True},
                                      {'name': 'work_id',
                                       'in': 'path',
                                       'required': True,
                                       'explode': True}],
                           'content': 'application/json',
                           'security': [{'bearer': []}]},
 'create_child_org': {'id': 'create_child_org',
                      'method': 'POST',
                      'path': '/api/v3/orgs/{organization_id}/children',
                      'params': [{'name': 'Authorization',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'Account-Type',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'organization_id',
                                  'in': 'path',
                                  'required': True,
                                  'explode': True}],
                      'content': 'application/json',
                      'security': [{'bearer': []}]},
 'transfer_org_ownership': {'id': 'transfer_org_ownership',
                            'method': 'POST',
                            'path': '/api/v3/orgs/{organization_id}/members/{member_id}/transfer-ownership',
                            'params': [{'name': 'Authorization',
                                        'in': 'header',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'Account-Type',
                                        'in': 'header',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'organization_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True},
                                       {'name': 'member_id',
                                        'in': 'path',
                                        'required': True,
                                        'explode': True}],
                            'content': None,
                            'security': [{'bearer': []}]},
 'move_plant_organization': {'id': 'move_plant_organization',
                             'method': 'POST',
                             'path': '/api/v3/orgs/{organization_id}/plants/{plant_id}/move',
                             'params': [{'name': 'Authorization',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'Account-Type',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'organization_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'plant_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'get_plant_comment': {'id': 'get_plant_comment',
                       'method': 'GET',
                       'path': '/api/v3/plants/{plant_id}/comments/{comment_id}',
                       'params': [{'name': 'Authorization',
                                   'in': 'header',
                                   'required': True,
                                   'explode': True},
                                  {'name': 'Account-Type',
                                   'in': 'header',
                                   'required': True,
                                   'explode': True},
                                  {'name': 'plant_id',
                                   'in': 'path',
                                   'required': True,
                                   'explode': True},
                                  {'name': 'comment_id',
                                   'in': 'path',
                                   'required': True,
                                   'explode': True},
                                  {'name': 'If-Match',
                                   'in': 'header',
                                   'required': False,
                                   'explode': True},
                                  {'name': 'If-None-Match',
                                   'in': 'header',
                                   'required': False,
                                   'explode': True},
                                  {'name': 'If-Modified-Since',
                                   'in': 'header',
                                   'required': False,
                                   'explode': True},
                                  {'name': 'If-Unmodified-Since',
                                   'in': 'header',
                                   'required': False,
                                   'explode': True}],
                       'content': None,
                       'security': [{'bearer': []}]},
 'list_device_transition_logs': {'id': 'list_device_transition_logs',
                                 'method': 'GET',
                                 'path': '/api/v3/plants/{plant_id}/logs/device',
                                 'params': [{'name': 'Authorization',
                                             'in': 'header',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'Account-Type',
                                             'in': 'header',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'plant_id',
                                             'in': 'path',
                                             'required': True,
                                             'explode': True},
                                            {'name': 'page',
                                             'in': 'query',
                                             'required': False,
                                             'explode': True},
                                            {'name': 'size',
                                             'in': 'query',
                                             'required': False,
                                             'explode': True},
                                            {'name': 'sort',
                                             'in': 'query',
                                             'required': False,
                                             'explode': True}],
                                 'content': None,
                                 'security': [{'bearer': []}]},
 'list_ess_transition_logs': {'id': 'list_ess_transition_logs',
                              'method': 'GET',
                              'path': '/api/v3/plants/{plant_id}/logs/ess',
                              'params': [{'name': 'Authorization',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'Account-Type',
                                          'in': 'header',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'plant_id',
                                          'in': 'path',
                                          'required': True,
                                          'explode': True},
                                         {'name': 'page',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'size',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True},
                                         {'name': 'sort',
                                          'in': 'query',
                                          'required': False,
                                          'explode': True}],
                              'content': None,
                              'security': [{'bearer': []}]},
 'list_plant_memos': {'id': 'list_plant_memos',
                      'method': 'GET',
                      'path': '/api/v3/plants/{plant_id}/memos',
                      'params': [{'name': 'Authorization',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'Account-Type',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'plant_id',
                                  'in': 'path',
                                  'required': True,
                                  'explode': True}],
                      'content': None,
                      'security': [{'bearer': []}]},
 'start_plant_memo_thread': {'id': 'start_plant_memo_thread',
                             'method': 'POST',
                             'path': '/api/v3/plants/{plant_id}/memos/start_thread',
                             'params': [{'name': 'Authorization',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'Account-Type',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'plant_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'get_plant_memo': {'id': 'get_plant_memo',
                    'method': 'GET',
                    'path': '/api/v3/plants/{plant_id}/memos/{comment_id}',
                    'params': [{'name': 'Authorization',
                                'in': 'header',
                                'required': True,
                                'explode': True},
                               {'name': 'Account-Type',
                                'in': 'header',
                                'required': True,
                                'explode': True},
                               {'name': 'plant_id',
                                'in': 'path',
                                'required': True,
                                'explode': True},
                               {'name': 'comment_id',
                                'in': 'path',
                                'required': True,
                                'explode': True},
                               {'name': 'If-Match',
                                'in': 'header',
                                'required': False,
                                'explode': True},
                               {'name': 'If-None-Match',
                                'in': 'header',
                                'required': False,
                                'explode': True},
                               {'name': 'If-Modified-Since',
                                'in': 'header',
                                'required': False,
                                'explode': True},
                               {'name': 'If-Unmodified-Since',
                                'in': 'header',
                                'required': False,
                                'explode': True}],
                    'content': None,
                    'security': [{'bearer': []}]},
 'edit_plant_memo': {'id': 'edit_plant_memo',
                     'method': 'POST',
                     'path': '/api/v3/plants/{plant_id}/memos/{comment_id}/edit',
                     'params': [{'name': 'Authorization',
                                 'in': 'header',
                                 'required': True,
                                 'explode': True},
                                {'name': 'Account-Type',
                                 'in': 'header',
                                 'required': True,
                                 'explode': True},
                                {'name': 'plant_id',
                                 'in': 'path',
                                 'required': True,
                                 'explode': True},
                                {'name': 'comment_id',
                                 'in': 'path',
                                 'required': True,
                                 'explode': True}],
                     'content': 'application/json',
                     'security': [{'bearer': []}]},
 'reply_plant_memo': {'id': 'reply_plant_memo',
                      'method': 'POST',
                      'path': '/api/v3/plants/{plant_id}/memos/{comment_id}/reply',
                      'params': [{'name': 'Authorization',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'Account-Type',
                                  'in': 'header',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'plant_id',
                                  'in': 'path',
                                  'required': True,
                                  'explode': True},
                                 {'name': 'comment_id',
                                  'in': 'path',
                                  'required': True,
                                  'explode': True}],
                      'content': 'application/json',
                      'security': [{'bearer': []}]},
 'change_plant_memo_state': {'id': 'change_plant_memo_state',
                             'method': 'POST',
                             'path': '/api/v3/plants/{plant_id}/memos/{comment_id}/state',
                             'params': [{'name': 'Authorization',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'Account-Type',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'plant_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'comment_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True}],
                             'content': 'application/json',
                             'security': [{'bearer': []}]},
 'get_latest_edge_metrics': {'id': 'get_latest_edge_metrics',
                             'method': 'GET',
                             'path': '/api/v3/plants/{plant_id}/metrics/edge/latest',
                             'params': [{'name': 'Authorization',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'Account-Type',
                                         'in': 'header',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'plant_id',
                                         'in': 'path',
                                         'required': True,
                                         'explode': True},
                                        {'name': 'asset_id',
                                         'in': 'query',
                                         'required': False,
                                         'explode': True}],
                             'content': None,
                             'security': [{'bearer': []}]}}
